# GitHub Metrics Auto-Update Workflow

name: Metrics

on:
  schedule:
    - cron: "59 1 * * *"
  workflow_dispatch:

concurrency:
  group: metrics-generation
  cancel-in-progress: false

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      USERNAME: muriarty1893
      METRICS_TOKEN: ${{ secrets.METRICS_TOKEN != '' && secrets.METRICS_TOKEN || github.token }}
    steps:
      - name: Base Metrics - Core Stats & Activity
        if: ${{ always() }}
        uses: lowlighter/metrics@v3.34
        with:
          filename: asset/base.svg
          token: ${{ env.METRICS_TOKEN }}
          user: ${{ env.USERNAME }}
          base: header, activity, community, repositories
          plugin_lines: yes

      - name: Isometric Commit Calendar
        if: ${{ always() }}
        uses: lowlighter/metrics@v3.34
        with:
          filename: asset/isocalendar.svg
          token: ${{ env.METRICS_TOKEN }}
          user: ${{ env.USERNAME }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
